### ISSUE TITLE
Do we need/prefer quotation marks in Xalgo rules?

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/general-examples#10]
I see that Ryan placed quote marks around each of the elements in the Singapore sample rule -- well, he was at least making it consistent:
https://github.com/Xalgorithms/lib-rules-int-scala/commit/fa9b5aed0396234882ccb7eaeb8bf04e66bdbf31#diff-5ef2197027eadebb9d0f9655d7a05937

A question for both of you:

Given that XalgoAuthor currently requires the quote marks, well, should it by design?  Are they there because it was a default syntax, or because they add info to a Xalgo expression?

If the quote marks don't add info, is it easy enough, and reasonable, to tweak XalgoAuthor to not require them? 

To my mind, keeping Xalgo free from such requirements helps to minimize the syntax error rate amongst authors. But maybe removing them creates other problems.

**Comment by karfai** [comment]
No, we don't. The original file was invalid JSON. The quotes are required in the table expressions JSON.

**Comment by jpotvin** [comment]
RE: No, we don't. The original file was invalid JSON. The quotes are
required in the table expressions JSON.


That confused me: "No, we don't.... The quotes are required"


Joseph Potvin
Executive Director, Xalgorithms Foundation
Mobile: 819-593-5983
jpotvin@xalgorithms.org
https://www.xalgorithms.org

**Comment by karfai** [comment]
So... There's nothing *wrong* with the Xalgo that @RyanFleck posted previously. Therefore, there is no discussion required about quotes in *that* part of the rule expression. But, his previous **table** additions for this *test run* were **invalid JSON** (we express tables in JSON when we upload them to GitHub). The changes he made were a correction to that invalid JSON. JSON key-value sets (objects) **must have** quoted strings as the keys. The values **must be** strings, numbers or booleans (thus the error message he saw). Free variables (which is what the *unquoted strings* would be in JS, not JSON) are not permitted in the format.

**Comment by jpotvin** [comment]
I'll await the weekly call for further clarification (i.e. the discussion
required is just to clear up some minor confusion in my cranium).

Joseph
