### ISSUE TITLE
.list_id versus .list_name

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/general-examples#14]
Looking at:
> WHEN envelope:parties.supplier.industry.list_id == 'ISIC';
> WHEN envelope:parties.supplier.industry.value == 'G4711';
> WHEN item:classification.list_name == 'UNSPSC';
> WHEN item:classification.value == '506505';

Shoulldn't .list_id and .list_name both be either one or the other?  Probably .list_name is best since _id tends to refer to a more structured _id system and these are just acronyms.

**Comment by karfai** [comment]
Yes. This is a correct assessment. I'll look into why they are represented this way and make changes where warranted.

**Comment by karfai** [comment]
The [compute platform](https://github.com/Xalgorithms/interlibr) as it is currently implemented [has changed](https://development.xalgorithms.org/architecture/core.architecture/). This is no longer relevant.
