### ISSUE TITLE
Positive or negative value in the reductions_by_distance table? 

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/general-examples#2]
Should the $ values in this table be postive or negative?
https://github.com/Xalgorithms/general-examples/blob/master/qc-gas-tax/reductions_by_distance.json

Should the rule's formula add or subtract?

**Comment by karfai** [comment]
They should be positive. The final revision of the document adds a UBL allowance to the document where charge='false', indicating a discount. The original price of the item is not modified, but the final totals (which are generated values) would be updated in Lichen.
