### ISSUE TITLE
Where's the "a" in the .xalgo rule?

### ISSUE THREAD

**Issue by jpotvin** [Xalgorithms/general-examples#5]
In your updated .xalgo file for the a-plus-b example, where's the "a" that the invoice's "a" would map to?  I had "WHEN item == 'a'   ...  such as: buyer buys item called "a" for $2.00.

**Comment by karfai** [comment]
"a" is @price.value on line 14. It's also "c".... We can put it somewhere else, if you like, but I think this is good enough.

**Comment by jpotvin** [comment]
Your current rule would run on EVERY invoice in the CA jurisdiction. I want it to run only when "a" is present. 
"a" is the name of the item, and its price is "2.00" 
"b" is the name of the flat fee, and its amount is "3.00"

(Sorry for giving this info bass-ackwards -- I'm actually 'discovering' how to think about this by working on it.)

**Comment by jpotvin** [comment]
RE: [my comment] "Your current rule would run on EVERY invoice in the CA jurisdiction. I want it to run only when "a" is present.

Is this because FIRST Interlibre checks for all rules in effect for the relevent jurisdictions, and only SECOND checks for applicability?

**Comment by karfai** [comment]
Yes. That's the search order for rules.
